X = int(input())
H = int(input())
M = int(input())
a = int(X // 60)
b = int(H + a)
c = int(a * 60)
d = int(X - c)
e = int(M + d)
f = int(e // 60)
g = int(f + b)
h = int(f * 60)
j = int(e - h)
print(g)
print(j)
